### ISSUE TITLE
Can this work for Ruined Fooocus too?

### ISSUE THREAD

**Issue by ItsNoted** [toutjavascript/Fooocus-Log-Viewer#2]
I use Ruined Fooocus because it has a few more options I like. I thought it would work for RF but it does not seem to work for some reason. Is there a quick fix for that? Thanks for this!

(It does work for regular Fooocus)

**Comment by toutjavascript** [comment]
I will try on ruined fooocus

**Comment by ItsNoted** [comment]
Let me know how it goes.

**Comment by toutjavascript** [comment]
Hello
I am trying since 3 days to install Ruined, but it is hard : python errors and low internet connexion 
I hope I will be able to test it next few days

**Comment by ItsNoted** [comment]
> Hello I am trying since 3 days to install Ruined, but it is hard : python errors and low internet connexion I hope I will be able to test it next few days

Ok thank you. It is very similar, just a forked and modified version. Not too much difference.

**Comment by toutjavascript** [comment]
Ruined Fooocus doesn't log actions in a log.html file.
So this extension cannot be used
Images generated don't contain exif datas
So it is not possible to retrieve history actions

**Comment by ItsNoted** [comment]
Is exif data and meta data different? Because they do contain png meta data.

**Comment by toutjavascript** [comment]
You are right. Prompts are stored in the png generated by ruined
But the extension works with log.html file
You should use Breadboard to view all images

**Comment by toutjavascript** [comment]
Not possible to make this log viewer available on Ruined
