### ISSUE TITLE
Sound notification

### ISSUE THREAD

**Issue by ItsNoted** [toutjavascript/Fooocus-Log-Viewer#3]
I use [Breadboard](https://github.com/cocktailpeanut/breadboard) (which is no longer under development sadly) for viewing my images but I want to get away from it due to lack of updates.

Can a subtle popping sound be added to notify us when new images are added like Breadboard does?

**Comment by toutjavascript** [comment]
Good idea.
Il will look at the github. it was made by [cocktailpeanut](https://github.com/cocktailpeanut), a great developer with pinokio as new project

**Comment by ItsNoted** [comment]
> Good idea. Il will look at the github. it was made by [cocktailpeanut](https://github.com/cocktailpeanut), a great developer with pinokio as new project

Yep, very good app!

**Comment by toutjavascript** [comment]
Done with checkbox to activate or not sound
