### ISSUE TITLE
Auto reload by default and a couple other requests

### ISSUE THREAD

**Issue by ItsNoted** [toutjavascript/Fooocus-Log-Viewer#4]
Hey, sorry for opening more request issues. Not even sure if you are doing requests.

Any way to get auto reload on by default? Or allow us to add a parameter with the date and option to add auto reload to the URL so when we view the link those settings are checked on the appropriate date?

How about on the main page it just shows the latest images instead of having to select a folder? (thought I'd ask this one here instead of opening another issue request)

Any way to just tap the image to enlarge and view details so we don't have to click the magnifying glass? (this would work better on mobile)

**Comment by toutjavascript** [comment]
Thanks for all ideas
I will work on that this week

**Comment by ItsNoted** [comment]
Thanks for considering :)

**Comment by toutjavascript** [comment]
Hi

New release is online
Thanks for ideas

**Comment by toutjavascript** [comment]
All done :)
