### ISSUE TITLE
Do not show deleted images

### ISSUE THREAD

**Issue by docppp** [toutjavascript/Fooocus-Log-Viewer#6]
Often I'm not even close to be happy about the result and I delete many files in output folder. Embedded history log skips those entries and I think this log viewer should as well.
![obraz](https://github.com/toutjavascript/Fooocus-Log-Viewer/assets/29142757/4fa52417-1c9e-4abb-9072-05225b374ee6)

**Comment by toutjavascript** [comment]
Yep 
It's a good idea. 
I will add a config choice to view or hide all deleted images (with a not very visible counter)

Thanks for message
